/**
 * Generates formatted forensic markdown report.
 * @param {object} results
 * @returns {string}
 */
export function generateMarkdownReport(results) {
  const {
    risk_score,
    verdict,
    verdict_badge,
    summary,
    extracted_fields = {},
    signals = [],
    execution_time_seconds,
  } = results;

  const dateStr = new Date().toUTCString();

  let md = `# Job Scam & Recruiter Verification Forensic Brief\n\n`;
  md += `**Generated:** ${dateStr}\n`;
  md += `**Execution Time:** ${execution_time_seconds}s\n\n`;

  md += `## 1. Executive Verdict\n\n`;
  md += `- **Risk Score:** ${risk_score} / 100\n`;
  md += `- **Classification:** ${verdict.toUpperCase()} (${verdict_badge})\n`;
  md += `- **Summary:** ${summary}\n\n`;

  md += `## 2. Extracted Entities\n\n`;
  md += `| Field | Extracted Value |\n`;
  md += `|---|---|\n`;
  md += `| **Company Name** | ${extracted_fields.company_name || "N/A"} |\n`;
  md += `| **Job Title** | ${extracted_fields.job_title || "N/A"} |\n`;
  md += `| **Recruiter Name** | ${extracted_fields.recruiter_name || "N/A"} |\n`;
  md += `| **Claimed Domain / Email** | ${extracted_fields.contact_email || extracted_fields.claimed_domain || "N/A"} |\n`;
  md += `| **Distinctive Quote** | ${extracted_fields.distinctive_phrase || "N/A"} |\n\n`;

  md += `## 3. OSINT SerpApi Evidence Breakdown\n\n`;
  md += `| Signal | Engine | Delta | Status | Finding | Evidence Link |\n`;
  md += `|---|---|---|---|---|---|\n`;

  for (const s of signals) {
    const delta = s.score_delta > 0 ? `+${s.score_delta}` : `${s.score_delta}`;
    const link = s.evidence_url || s.search_url || "N/A";
    md += `| **${s.signal_name}** | \`${s.engine}\` | \`${delta}\` | **${s.status.toUpperCase()}** | ${s.finding} | [View Query / Result](${link}) |\n`;
  }

  md += `\n---\n*Report generated by TrueRecruit OSINT Engine backed by SerpApi.*\n`;
  return md;
}

/**
 * Downloads a text/JSON file in browser.
 */
export function downloadFile(content, filename, contentType = "text/markdown") {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
